services:
  habitor.api:
    image: ${DOCKER_REGISTRY-}habitorapi
    environment:
      # Seq
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://habitor.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://habitor.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - ASPNETCORE_ENVIRONMENT=Development 
    build:
      context: .
      dockerfile: src/Habitor.Api/Dockerfile
    depends_on:
      - habitor.postgres
    ports:
      - 5000:8080
      - 5001:8081

  habitor.postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: devhabit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - ./.container/postgres-data:/var/lib/postgresql/data

  habitor.seq:
    image: datalust/seq:2024.3
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - 8080:80
      - 5341:5341
    volumes:
      - ./.container/seq-data:/data

  habitor.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888