name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '9.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore HabitorDeveloper.sln

      - name: Build solution
        run: dotnet build HabitorDeveloper.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test HabitorDeveloper.sln --configuration Release --no-restore --no-build --logger "trx"

      - name: Publish API project
        run: dotnet publish src/Habitor.Api --configuration Release --no-restore --no-build
